palette = "catppuccin_mocha"

add_newline = false

command_timeout = 10000

format="""$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$java\
$python\
$rust\
$terraform\
$aws\
$line_break\
$jobs\
$status\
$shell\
$character"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
truncation_length = 0
truncate_to_repo = true
read_only = " RO"
style = "bold lavender"

[python]
disabled = false
style = "bold green"
symbol = "\ue73c "
format = '[${symbol}($virtualenv)]($style) '

[terraform]
symbol = "tf "
format = "[$symbol$version]($style) "
disabled = false

[aws]
format = '[$symbol($profile )]($style)'
style = "bold maroon"
symbol = "ðŸ…° "

[character]
error_symbol = "[Î»](bold red)"
success_symbol = "[Î»](bold green)"

[git_branch]
style = "bold mauve"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = "bold mauve"
