add_newline = false

command_timeout = 10000

format="""
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$java\
$python\
$rust\
$terraform\
$aws\
$line_break\
$jobs\
$status\
$shell\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = true
read_only = " RO"
style = "bold #50fa7b"

[python]
disabled = false
style = "bold green"
format = '[${symbol}($virtualenv)]($style) '

[terraform]
symbol = "tf "
format = "[$symbol$version]($style) "
disabled = false

[aws]
format = '[$symbol($profile )]($style)'
style = "bold #ffb86c"
symbol = "ðŸ…° "

[character]
error_symbol = "[Î»](bold #ff5555)"
success_symbol = "[Î»](bold #50fa7b)"

[git_branch]
style = "bold #ff79c6"
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
#style = "bold #ff5555"
style = "bold #ff79c6"
